"""Project-local tools for reproducible pulse-shape analysis."""

from .pipeline import (
    DETECTOR_LABELS,
    EnergyShapeConfig,
    PipelineConfig,
    audit_waveforms,
    analyze_energy_binned_shapes,
    assess_energy_binning_sensitivity,
    characterize_processed_shapes,
    configure_plotly,
    discover_project,
    inventory_sources,
    load_root_event_metadata,
    plot_processed_shapes,
    plot_energy_binned_shape_distributions,
    plot_energy_shape_scores,
    plot_qc_flagged_waveforms,
    plot_raw_groups,
    preprocess_waveforms,
    print_audit,
    print_characteristics,
    print_energy_shape_analysis,
    print_energy_binning_sensitivity,
    print_inventory,
    print_quality_summary,
    print_qc_flag_summary,
    sample_waveforms,
    sample_run_waveforms,
    save_processed_data,
    save_energy_shape_analysis,
    save_energy_binning_sensitivity,
    save_root_event_metadata,
    save_sample,
    summarize_and_validate,
    summarize_qc_flags,
)

__all__ = [name for name in globals() if not name.startswith("_")]
